FROM bdd-tester-ui-build:v0.0.7 AS builder

COPY env.d.ts postcss.config.js tailwind.config.js tsconfig.app.json tsconfig.json tsconfig.node.json vite.config.ts ./
COPY index.html .
COPY public/ public/
COPY src/ src/

ARG APP_VERSION=dev

RUN VITE_APP_VERSION=$APP_VERSION yarn run build

FROM nginxinc/nginx-unprivileged:1.27-alpine3.21-slim

WORKDIR /usr/share/nginx/html/bdd-tester/ui

COPY --from=builder /app/dist .
