name: Continuous Integration

on:
  push:
    branches:
      - "*"

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - run: yarn install
      - uses: sibiraj-s/action-eslint@v3
        with:
          extensions: 'css,html,js,jsx,ts,tsx,vue'
          all-files: true
          annotations: true
